name: Rust

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  audit:
    name: Audit Rust vulnerabilities
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        use-tool-cache: true

    - run: cargo audit

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings

      - name: set nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

      - name: coverage
        uses: actions-rs/grcov@v0.1

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.coverage.outputs.report }}
          fail_ci_if_error: true
